name: immich_timeline_generator
description: A console application to generate Google Timeline from Immich photos.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.2.0
  args: ^2.4.2
  intl: ^0.19.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
